### PR TITLE
geospatial extensions

### PR DESCRIPTION
**Pull request by takinbo**

### CODE REVIEW

**Comment by blynchNDI** [comment]
@takinbo - the build seems to be failing - I tried clearing out all docker images and volumes, but it still gives the following error:

Service 'postgres' failed to build: The command '/bin/sh -c set -ex && apk add --no-cache --virtual .fetch-deps ca-certificates openssl tar && wget -O postgis.tar.gz "https://github.com/postgis/postgis/archive/$POSTGIS_VERSION.tar.gz" && echo "$POSTGIS_SHA256 *postgis.tar.gz" | sha256sum -c - && mkdir -p /usr/src/postgis && tar --extract --file postgis.tar.gz --directory /usr/src/postgis --strip-components 1 && rm postgis.tar.gz && apk add --no-cache --virtual .build-deps autoconf automake g++ json-c-dev libtool libxml2-dev make perl && apk add --no-cache --virtual .build-deps-edge --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing --repository http://dl-cdn.alpinelinux.org/alpine/edge/main gdal-dev geos-dev proj-dev protobuf-c-dev && cd /usr/src/postgis && ./autogen.sh && ./configure && make && make install && apk add --no-cache --virtual .postgis-rundeps json-c && apk add --no-cache --virtual .postgis-rundeps-edge --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing --repository http://dl-cdn.alpinelinux.org/alpine/edge/main geos gdal proj protobuf-c && cd / && rm -rf /usr/src/postgis && apk del .fetch-deps .build-deps .build-deps-edge' returned a non-zero code: 1

**Comment by takinbo** [comment]
It appears that the build isn't using the version information contained in the environment. Can you share details about the docker version running on the box? Also, I suspect this is being done through `docker-compose`?

**Comment by blynchNDI** [comment]
Here's the docker information:
docker version is 18.06.1-ce
docker-compose version is 1.23.2

**Comment by blynchNDI** [comment]
I tried running the docker-compose up -d again, and I got the following:

ERROR: unsatisfiable constraints:
  .postgis-rundeps-edge (missing):
    required by: world[.postgis-rundeps-edge=20190705.145944]

Let me know if there's other information that would be useful

**Comment by blynchNDI** [comment]
I've tried running `docker-compose up -d` (as well as `docker-compose up -d --force-recreate --renew-anon-volumes --build`) some more times and it looks like it's now failing consistently here:
Screenshot from 2019-07-05 15-10-03

**Comment by takinbo** [comment]
@blynchNDI looks like the postgres container is now building correctly and that the issue is with the apollo container. The last update was useful and I'll attempt a fresh build on my workstation and if I can replicate it, I will work on a fix.

**Comment by takinbo** [comment]
@blynchNDI I was able to replicate the problem and patched it. Turns out a new package we installed requires a package called geos which must be installed in alpine containers explicitly.

**Comment by blynchNDI** [comment]
@takinbo Ok good progress! The build completed with a successful exit code and all the containers were built. The containers apart from the Redis one seem to be having issues though. The postgres container went down with the following error, but stayed up once I restarted it:

`/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/postgis.sh
/docker-entrypoint-initdb.d/postgis.sh: line 13: syntax error: bad substitution`

The two apollo application containers though keep going down immediately after being restarted, giving the error below:

`/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/functions.py:68: SAWarning: The GenericFunction 'array_agg' is already registered and is going to be overriden.
  "is going to be overriden.".format(identifier))
Traceback (most recent call last):
  File "./manage.py", line 15, in <module>
    from apollo.core import db
  File "/app/apollo/__init__.py", line 13, in <module>
    from apollo import assets, models, services
  File "/app/apollo/models.py", line 5, in <module>
    from apollo.locations.models import (  # noqa
  File "/app/apollo/locations/models.py", line 3, in <module>
    from geoalchemy2 import Geometry
  File "/usr/local/lib/python3.6/site-packages/geoalchemy2/__init__.py", line 1, in <module>
    from .types import (  # NOQA
  File "/usr/local/lib/python3.6/site-packages/geoalchemy2/types.py", line 17, in <module>
    from .shape import to_shape
  File "/usr/local/lib/python3.6/site-packages/geoalchemy2/shape.py", line 10, in <module>
    import shapely.wkb
  File "/usr/local/lib/python3.6/site-packages/shapely/wkb.py", line 4, in <module>
    from shapely import geos
  File "/usr/local/lib/python3.6/site-packages/shapely/geos.py", line 76, in <module>
    free = load_dll('c').free
  File "/usr/local/lib/python3.6/site-packages/shapely/geos.py", line 56, in load_dll
    libname, fallbacks or []))
OSError: Could not find lib c or load any of its variants [].
`

**Comment by blynchNDI** [comment]
Adding a screenshot because it's probably easier to read:
Screenshot from 2019-07-05 19-10-32

**Comment by takinbo** [comment]
@blynchNDI I updated the base image for the Apollo image and so should resolve this issue. Please report if you're still unable to get it running.

**Comment by blynchNDI** [comment]
The automated pipeline spun up the qa site successfully. Thanks @takinbo!

**Pull request merged**
