### PR TITLE
fix: remove CLI commands

### PR DESCRIPTION
**Pull request by dodumosu**
addresses #665 by removing commands that can be performed using the web UI

### CODE REVIEW

**Comment by blynchNDI** [comment]
@dodumosu would it be possible to leave in the ./manage.py create_user function? That one seems to be working without a problem at least right now, and is useful for if we ever need to access the frontend of an old apollo site where we don't have the credentials (or on the off chance a user somehow deletes all the admin accounts on the site and needs to create a new one)

**Comment by blynchNDI** [comment]
(Ideally it would be great to keep as many of the commands as possible, but I'm not sure if updates have made them hard to maintain)

**Comment by takinbo** [comment]
> @dodumosu would it be possible to leave in the ./manage.py create_user function? That one seems to be working without a problem at least right now, and is useful for if we ever need to access the frontend of an old apollo site where we don't have the credentials (or on the off chance a user somehow deletes all the admin accounts on the site and needs to create a new one)

We can include instructions on how to create an admin user using the python shell `./manage.py shell` as opposed to keeping any part of the management commands.

**Comment by blynchNDI** [comment]
@takinbo sounds good - having the functionality available via the python shell is entirely fine

**Pull request merged**
