### PR TITLE
fix: allow equatorial coordinates in location uploads

### PR DESCRIPTION
**Pull request by dodumosu**
also fixes a typo

### CODE REVIEW

**Comment by blynchNDI** [comment]
@takinbo the apolloqa site doesn't seem to be loading - the output from the failed build attempt is below. Right now the build script is only removing the current docker containers and trying to build new ones (`sudo docker-compose up -d --force-recreate --renew-anon-volumes --build`), so let me know if I should try clearing out anything else on the server.

[stderr]Building web
[stdout]Step 1/8 : FROM python:3.6
[stdout] ---> 48c06762acf0
[stdout]Step 2/8 : LABEL maintainer="Tim Akinbo <takinbo@timbaobjects.com>"
[stdout] ---> Using cache
[stdout] ---> ba10ac9401ff
[stdout]Step 3/8 : ADD . /app/
[stdout] ---> 6e4fe1b119c9
[stdout]Step 4/8 : RUN pip install --no-cache-dir -r /app/requirements/prod.txt
[stdout] ---> Running in b78ed6c37891
[stderr]Service 'web' failed to build: failed to start shim: exec: "docker-containerd-shim": executable file not found in $PATH: unknown

**Comment by takinbo** [comment]
@blynchNDI does look like a docker issue. Can you exclude `force-recreate` and `renew-anon-volumes`. I think only using `docker-compose up -d --build` should be sufficient.

**Comment by blynchNDI** [comment]
Some negative progress unfortunately. I simplified the build command and cleared out all the docker volumes, images, etc. and built it from scratch, but clearing everything seems to have caused the build to fail with the same error now for postgres

[stdout] ---> Running in 46cf44e42249
[stderr]Service 'postgres' failed to build: failed to start shim: exec: "docker-containerd-shim": executable file not found in $PATH: unknown

**Comment by blynchNDI** [comment]
Ok, based on a quick skim of [this page](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=920597), running `systemctl restart docker` seems to have fixed things. I'll report back to confirm if the build finishes successfully.

**Comment by blynchNDI** [comment]
It's now failing at a different point ...looks like maybe postgis-rundeps-edge is missing?

`ERROR: unsatisfiable constraints:
  .postgis-rundeps-edge (missing):
    required by: world[.postgis-rundeps-edge=20190709.145638]
ERROR: Service 'postgres' failed to build: The command '/bin/sh -c set -ex         && apk add --no-cache --virtual .fetch-deps         ca-certificates         openssl         tar         && wget -O postgis.tar.gz "https://github.com/postgis/postgis/archive/$POSTGIS_VERSION.tar.gz"     && echo "$POSTGIS_SHA256 *postgis.tar.gz" | sha256sum -c -     && mkdir -p /usr/src/postgis     && tar         --extract         --file postgis.tar.gz         --directory /usr/src/postgis         --strip-components 1     && rm postgis.tar.gz         && apk add --no-cache --virtual .build-deps         autoconf         automake         g++         json-c-dev         libtool         libxml2-dev         make         perl         && apk add --no-cache --virtual .build-deps-edge         --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing         --repository http://dl-cdn.alpinelinux.org/alpine/edge/main         gdal-dev         geos-dev         proj-dev         protobuf-c-dev     && cd /usr/src/postgis     && ./autogen.sh     && ./configure     && make     && make install     && apk add --no-cache --virtual .postgis-rundeps         json-c     && apk add --no-cache --virtual .postgis-rundeps-edge         --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing         --repository http://dl-cdn.alpinelinux.org/alpine/edge/main         geos         gdal         proj         protobuf-c     && cd /     && rm -rf /usr/src/postgis     && apk del .fetch-deps .build-deps .build-deps-edge' returned a non-zero code: 1`

**Comment by takinbo** [comment]
Could you try restarting the box. `docker-containerd-shim` is a part of docker and should exist unless something is wrong with the docker installation.

**Comment by takinbo** [comment]
Try with `docker-compose up -d --build --no-cache`. Builds still succeed on my end.

**Comment by blynchNDI** [comment]
Ok, a bit weird, but it's up and working. I rebooted the server, and `docker-compose up -d` didn't work but `sudo docker-compose up -d --force-recreate --renew-anon-volumes --build` did end successfully. The Redis and the Worker container were started, and the Postgres and Web containers had gone down, but restarted and stayed up successfully.

**Comment by takinbo** [comment]
Good to know. Let's see how it does during the next update. Might want to leave `docker-compose up -d --force-recreate --renew-anon-volumes --build` as the default now.

**Comment by blynchNDI** [comment]
Yeah that makes sense, will do.

**Comment by blynchNDI** [comment]
@takinbo Interestingly an older Apollo 3 demo site that we hadn't touched in a while went down just over a day ago, and the containers were giving the error below when I tried to restart them. Rebooting the server in this case solved the problem too. It sounds like though there may have been some update to docker/containerd-shim that was breaking things.


`Error response from daemon: failed to listen to abstract unix socket "/containerd-shim/moby/5ff936527e97bd4b965bbebb4c8a3e13dafc1dcdb1aa05d4d50a4021e84e789c/shim.sock": listen unix /containerd-shim/moby/5ff936527e97bd4b965bbebb4c8a3e13dafc1dcdb1aa05d4d50a4021e84e789c/shim.sock: bind: address already in use: unknown`

**Pull request merged**
